global using DotNetCore.CAP;
global using Vivi.Infrastructure.Entities;
global using Vivi.Infrastructure.IRepositories;
global using Vivi.Infrastructure.Repository.EfCore.Repositories;
global using Vivi.Infrastructure.Repository.EfCore.Transaction;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Storage;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using System.Data;